name: Enterprise CI/CD

on:
  push:
    branches: [feature/enterprise-cicd]
  release:
    types: [published]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/todo-api

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint || true   # lint errors -> warnings
      - name: SAST Security Scan
        run: npx snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run tests with coverage
        run: |
          npm run test -- --coverage \
            --coverageThreshold='{"global": {"branches": 85, "functions": 85, "lines": 85, "statements": 85}}'

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

  performance-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run container
        run: |
          docker run -d -p 5000:5000 --name todo-api $IMAGE_NAME:latest
          sleep 5
      - name: Run k6 load test
        run: |
          npm install -g k6
          k6 run perf-tests/p95.js
      - name: Cleanup
        run: docker rm -f todo-api

  container-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          severity: CRITICAL,HIGH
          exit-code: 1

  deploy-to-staging:
    runs-on: self-hosted
    needs: [performance-test, container-scan]
    steps:
      - name: Deploy via docker compose
        run: |
          docker compose -f docker-compose.staging.yml pull
          docker compose -f docker-compose.staging.yml up -d

  staging-smoke-tests:
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    steps:
      - name: Smoke Tests
        run: |
          curl -f http://staging-host:5000/health
          curl -f http://staging-host:5000/tasks
          curl -X POST -H "Content-Type: application/json" \
               -d '{"title":"test"}' http://staging-host:5000/tasks

  deploy-to-prod:
    runs-on: self-hosted
    needs: staging-smoke-tests
    if: success()
    steps:
      - name: Deploy via docker compose
        run: |
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d

  rollback:
    runs-on: self-hosted
    if: failure() && (needs.staging-smoke-tests.result == 'failure' || needs.performance-test.result == 'failure')
    steps:
      - name: Rollback to previous version
        run: |
          echo "Rolling back to previous stable version..."
          docker compose -f docker-compose.yml pull
          docker compose -f docker-compose.yml up -d
